spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:authenticationdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect